### ISSUE TITLE
RuntimeError: must forward with targets before backward

### ISSUE THREAD

**Issue by 1997MarsRover** [karpathy/llm.c#81]
tried to run:

```bash
     !OMP_NUM_THREADS=8 ./train_gpt2
   ```
RuntimeError:
```yaml
  [GPT-2]
  max_seq_len: 1024
  vocab_size: 50257
  num_layers: 12
  num_heads: 12
  channels: 768
  num_parameters: 124439808
  train dataset num_batches: 1192
  val dataset num_batches: 128
  num_activations: 73323776
  val loss 5.252006
  step 0: train loss 5.356172 (took 26772.736942 ms)
  Error: must forward with targets before backward
```
